# Proyecto de Inteligencia Artificial  
## Clasificación de riesgo crediticio (`Credit Score`)

En este proyecto se analiza un conjunto de datos de clientes con información demográfica y financiera, con el objetivo de **predecir el nivel de riesgo crediticio** de cada persona.

El flujo general será:

1. Exploración y descripción del dataset.
2. Preprocesamiento de datos (limpieza, tratamiento de nulos, codificación, escalado).
3. Entrenamiento y evaluación de modelos de clasificación.
4. Reducción de dimensionalidad con PCA.
5. Clustering (aprendizaje no supervisado).
6. Análisis y conclusiones finales.

# Descripción Detallada del Dataset

In [33]:
import pandas as pd
pd.set_option("display.max_columns", 50)

df = pd.read_csv("credit_score.csv")

# limpiar posibles espacios en nombres de columnas (por si acaso)
df.columns = df.columns.str.strip()

df.head()

C:\Users\COMPU\AppData\Local\Temp\ipykernel_13180\502030997.py:4: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("credit_score.csv")

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,11.27,4.0,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,NaN,11.27,4.0,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,_,4.0,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,4,6.27,4.0,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,NaN,11.27,4.0,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [34]:
# Tamaño del dataset (filas, columnas)
df.shape

(100000, 28)

In [35]:
# Lista de columnas
df.columns.tolist()

['ID',
 'Customer_ID',
 'Month',
 'Name',
 'Age',
 'SSN',
 'Occupation',
 'Annual_Income',
 'Monthly_Inhand_Salary',
 'Num_Bank_Accounts',
 'Num_Credit_Card',
 'Interest_Rate',
 'Num_of_Loan',
 'Type_of_Loan',
 'Delay_from_due_date',
 'Num_of_Delayed_Payment',
 'Changed_Credit_Limit',
 'Num_Credit_Inquiries',
 'Credit_Mix',
 'Outstanding_Debt',
 'Credit_Utilization_Ratio',
 'Credit_History_Age',
 'Payment_of_Min_Amount',
 'Total_EMI_per_month',
 'Amount_invested_monthly',
 'Payment_Behaviour',
 'Monthly_Balance',
 'Credit_Score']

In [36]:
df.isnull().sum().sort_values(ascending=False).head(15)

Monthly_Inhand_Salary       15002
Type_of_Loan                11408
Name                         9985
Credit_History_Age           9030
Num_of_Delayed_Payment       7002
Amount_invested_monthly      4479
Num_Credit_Inquiries         1965
Monthly_Balance              1200
ID                              0
Changed_Credit_Limit            0
Payment_Behaviour               0
Total_EMI_per_month             0
Payment_of_Min_Amount           0
Credit_Utilization_Ratio        0
Outstanding_Debt                0
dtype: int64

In [37]:
# Información general del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

In [38]:
#resumen estadístico:
df.describe(include="all")

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
count,100000,100000,100000,90015,100000,100000,100000,100000,84998.000000,100000.000000,100000.00000,100000.000000,100000,88592,100000.000000,92998,100000,98035.000000,100000,100000,100000.000000,90970,100000,100000.000000,95521,100000,98800,100000
unique,100000,12500,8,10139,1788,12501,16,18940,NaN,NaN,NaN,NaN,434,6260,NaN,749,4384,NaN,4,13178,NaN,404,3,NaN,91049,7,98792,3
top,0x1602,CUS_0xd40,January,Langep,38,#F%$D@*&8,_______,36585.12,NaN,NaN,NaN,NaN,3,Not Specified,NaN,19,_,NaN,Standard,1360.45,NaN,15 Years and 11 Months,Yes,NaN,__10000__,Low_spent_Small_value_payments,__-333333333333333333333333333__,Standard
freq,1,8,12500,44,2833,5572,7062,16,NaN,NaN,NaN,NaN,14386,1408,NaN,5327,2091,NaN,36479,24,NaN,446,52326,NaN,4305,25513,9,53174
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4194.170850,17.091280,22.47443,72.466040,NaN,NaN,21.068780,NaN,NaN,27.754251,NaN,NaN,32.285173,NaN,NaN,1403.118217,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3183.686167,117.404834,129.05741,466.422621,NaN,NaN,14.860104,NaN,NaN,193.177339,NaN,NaN,5.116875,NaN,NaN,8306.041270,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.645417,-1.000000,0.00000,1.000000,NaN,NaN,-5.000000,NaN,NaN,0.000000,NaN,NaN,20.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1625.568229,3.000000,4.00000,8.000000,NaN,NaN,10.000000,NaN,NaN,3.000000,NaN,NaN,28.052567,NaN,NaN,30.306660,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3093.745000,6.000000,5.00000,13.000000,NaN,NaN,18.000000,NaN,NaN,6.000000,NaN,NaN,32.305784,NaN,NaN,69.249473,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5957.448333,7.000000,7.00000,20.000000,NaN,NaN,28.000000,NaN,NaN,9.000000,NaN,NaN,36.496663,NaN,NaN,161.224249,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15204.633333,1798.000000,1499.00000,5797.000000,NaN,NaN,67.000000,NaN,NaN,2597.000000,NaN,NaN,50.000000,NaN,NaN,82331.000000,NaN,NaN,NaN,NaN

In [39]:
#distribución de la variable objetivo
df["Credit_Score"].value_counts()

Credit_Score
Standard    53174
Poor        28998
Good        17828
Name: count, dtype: int64

In [40]:
#porcentajes
df["Credit_Score"].value_counts(normalize=True)

Credit_Score
Standard    0.53174
Poor        0.28998
Good        0.17828
Name: proportion, dtype: float64

# PREPROCESAMIENTO

In [41]:
#Revisar valores nulos por columna
df.isnull().sum().sort_values(ascending=False)

Monthly_Inhand_Salary       15002
Type_of_Loan                11408
Name                         9985
Credit_History_Age           9030
Num_of_Delayed_Payment       7002
Amount_invested_monthly      4479
Num_Credit_Inquiries         1965
Monthly_Balance              1200
ID                              0
Changed_Credit_Limit            0
Payment_Behaviour               0
Total_EMI_per_month             0
Payment_of_Min_Amount           0
Credit_Utilization_Ratio        0
Outstanding_Debt                0
Credit_Mix                      0
Delay_from_due_date             0
Customer_ID                     0
Num_of_Loan                     0
Interest_Rate                   0
Num_Credit_Card                 0
Num_Bank_Accounts               0
Annual_Income                   0
Occupation                      0
SSN                             0
Age                             0
Month                           0
Credit_Score                    0
dtype: int64

>  Se excluyeron `ID`, `Customer_ID`, `Name`, `SSN` por ser identificadores

In [42]:
cols_drop = ["ID", "Customer_ID", "Name", "SSN"]
df = df.drop(columns=cols_drop)
df.head()

,Month,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,January,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,11.27,4.0,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,February,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,NaN,11.27,4.0,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,March,-500,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,_,4.0,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,April,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,4,6.27,4.0,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,May,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,NaN,11.27,4.0,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [43]:
#Detectar tipos de variables (numéricas vs categóricas)
df.dtypes

Month                        object
Age                          object
Occupation                   object
Annual_Income                object
Monthly_Inhand_Salary       float64
Num_Bank_Accounts             int64
Num_Credit_Card               int64
Interest_Rate                 int64
Num_of_Loan                  object
Type_of_Loan                 object
Delay_from_due_date           int64
Num_of_Delayed_Payment       object
Changed_Credit_Limit         object
Num_Credit_Inquiries        float64
Credit_Mix                   object
Outstanding_Debt             object
Credit_Utilization_Ratio    float64
Credit_History_Age           object
Payment_of_Min_Amount        object
Total_EMI_per_month         float64
Amount_invested_monthly      object
Payment_Behaviour            object
Monthly_Balance              object
Credit_Score                 object
dtype: object

In [44]:
#ver listas
num_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

num_cols, cat_cols

(['Monthly_Inhand_Salary',
  'Num_Bank_Accounts',
  'Num_Credit_Card',
  'Interest_Rate',
  'Delay_from_due_date',
  'Num_Credit_Inquiries',
  'Credit_Utilization_Ratio',
  'Total_EMI_per_month'],
 ['Month',
  'Age',
  'Occupation',
  'Annual_Income',
  'Num_of_Loan',
  'Type_of_Loan',
  'Num_of_Delayed_Payment',
  'Changed_Credit_Limit',
  'Credit_Mix',
  'Outstanding_Debt',
  'Credit_History_Age',
  'Payment_of_Min_Amount',
  'Amount_invested_monthly',
  'Payment_Behaviour',
  'Monthly_Balance',
  'Credit_Score'])

In [45]:
import numpy as np

# Lista de tokens que consideraremos como "faltantes"
rare_tokens = ["_", "__", "NA", "NM", "Not Specified", "__10000__", "!", "!@9#%8", "-","_______"]

df = df.replace(rare_tokens, np.nan)

> **Nota:** En `Age` se convierte la columna a numérica, se marcan como `NaN` las edades `< 18` o `> 100` y luego esos `NaN` se rellenan con la **mediana** de las edades válidas.

In [46]:
# Asegurar que Age sea numérica
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

# Marcar como NaN las edades fuera de un rango razonable
mask_age = (df["Age"] < 18) | (df["Age"] > 100)
df.loc[mask_age, "Age"] = np.nan

# Imputar Age con la mediana de las edades válidas
med_age = df["Age"].median()
df["Age"] = df["Age"].fillna(med_age)

df["Age"].describe()

count    100000.000000
mean         34.370670
std           9.440642
min          18.000000
25%          27.000000
50%          34.000000
75%          41.000000
max         100.000000
Name: Age, dtype: float64

> **Nota:** En las variables de dinero se recortan valores extremos usando los percentiles 1% y 99% para evitar que montos absurdamente grandes o pequeños distorsionen el modelo.

In [47]:
money_cols = [
    "Annual_Income",
    "Outstanding_Debt",
    "Amount_invested_monthly",
    "Monthly_Balance",
    "Total_EMI_per_month",
    "Credit_Utilization_Ratio",
    "Monthly_Inhand_Salary"
]

for col in money_cols:
    # Convertir a numérico por si quedó algo extraño
    df[col] = pd.to_numeric(df[col], errors="coerce")
    
    # Calcular percentiles 1 y 99
    q1 = df[col].quantile(0.01)
    q99 = df[col].quantile(0.99)
    
    # Recortar valores fuera de ese rango
    df[col] = df[col].clip(lower=q1, upper=q99)
    
    # Re-imputar posibles NaN nuevos con la mediana
    med = df[col].median()
    df[col] = df[col].fillna(med)

> **Nota:** En columnas clave como `Num_of_Loan` y `Changed_Credit_Limit` se fuerza el tipo numérico (desde `object`) y se rellenan los `NaN` generados en la conversión.

In [48]:
extra_num_cols = [
    "Num_of_Loan",
    "Changed_Credit_Limit",
    "Num_Credit_Inquiries",
    "Num_of_Delayed_Payment"
]

for col in extra_num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    med = df[col].median()
    df[col] = df[col].fillna(med)

df[extra_num_cols].describe()

,Num_of_Loan,Changed_Credit_Limit,Num_Credit_Inquiries,Num_of_Delayed_Payment
count,100000.000000,100000.000000,100000.000000,100000.000000
mean,2.790850,10.368345,27.326780,29.373010
std,60.987279,6.719627,191.293766,215.671804
min,-100.000000,-6.490000,0.000000,-3.000000
25%,2.000000,5.420000,3.000000,9.000000
50%,3.000000,9.400000,6.000000,14.000000
75%,5.000000,14.660000,9.000000,18.000000
max,1496.000000,36.970000,2597.000000,4397.000000

> Al final se verifica que no queden `NaN` residuales tras el preprocesamiento (por ejemplo, con `df.isna().sum()`).

In [49]:
# Columnas que son conteos
count_cols = ["Num_of_Loan", "Num_Credit_Inquiries", "Num_of_Delayed_Payment"]

# 1) Poner en NaN los valores negativos (imposibles)
for col in count_cols:
    df.loc[df[col] < 0, col] = np.nan

# 2) Imputar esos NaN con la mediana de cada columna
for col in count_cols:
    med = df[col].median()
    df[col] = df[col].fillna(med)

for col in count_cols:
    q99 = df[col].quantile(0.99)  # percentil 99
    df[col] = df[col].clip(upper=q99)

df[extra_num_cols].describe()

,Num_of_Loan,Changed_Credit_Limit,Num_Credit_Inquiries,Num_of_Delayed_Payment
count,100000.000000,100000.000000,100000.00000,100000.000000
mean,3.512340,10.368345,19.89320,13.580230
std,2.366936,6.719627,116.45226,5.962662
min,0.000000,-6.490000,0.00000,0.000000
25%,2.000000,5.420000,3.00000,10.000000
50%,3.000000,9.400000,6.00000,14.000000
75%,5.000000,14.660000,9.00000,18.000000
max,9.000000,36.970000,1067.00000,27.000000

In [50]:
# Asegurar que la columna es string
df["Credit_History_Age"] = df["Credit_History_Age"].astype(str)

# Extraer años y meses usando una expresión regular
age_parts = df["Credit_History_Age"].str.extract(
    r"(\d+)\s+Years?\s+and\s+(\d+)\s+Months?"
)

# Convertir a numérico
df["Credit_History_Years_num"] = pd.to_numeric(age_parts[0], errors="coerce")
df["Credit_History_Months_num"] = pd.to_numeric(age_parts[1], errors="coerce")

# Total de meses de historial
df["Credit_History_Total_Months"] = (
    df["Credit_History_Years_num"] * 12 +
    df["Credit_History_Months_num"]
)

# Imputar posibles NaN con la mediana
med_hist = df["Credit_History_Total_Months"].median()
df["Credit_History_Total_Months"] = df["Credit_History_Total_Months"].fillna(med_hist)

# (Opcional) versión en años como número flotante
df["Credit_History_Years_Float"] = df["Credit_History_Total_Months"] / 12

In [51]:
df["Credit_History_Total_Months"].describe()

count    100000.000000
mean        220.997160
std          95.133546
min           1.000000
25%         154.000000
50%         219.000000
75%         292.000000
max         404.000000
Name: Credit_History_Total_Months, dtype: float64

In [52]:
#Imputar categóricas con la moda
cat_cols = df.select_dtypes(include=["object"]).columns

for col in cat_cols:
    mode = df[col].mode(dropna=True)
    if len(mode) > 0:
        df[col] = df[col].fillna(mode[0])
    else:
        df[col] = df[col].fillna("Unknown")

In [53]:
df = df.drop(columns=[
    "Credit_History_Age",
    "Credit_History_Years_num",
    "Credit_History_Months_num"
])

In [58]:
time_cols = ["Delay_from_due_date"]

for col in time_cols:
    # Opcional: ver distribución antes
    print(df[col].describe())
    
    # Recortar outliers por percentiles 1 y 99
    q1 = df[col].quantile(0.01)
    q99 = df[col].quantile(0.99)
    df[col] = df[col].clip(lower=q1, upper=q99)

count    100000.000000
mean         21.068000
std          14.801421
min           0.000000
25%          10.000000
50%          18.000000
75%          28.000000
max          61.000000
Name: Delay_from_due_date, dtype: float64

In [57]:
df.isnull().sum().sort_values(ascending=False).head(15)

Month                          0
Num_Credit_Inquiries           0
Credit_History_Total_Months    0
Credit_Score                   0
Monthly_Balance                0
Payment_Behaviour              0
Amount_invested_monthly        0
Total_EMI_per_month            0
Payment_of_Min_Amount          0
Credit_Utilization_Ratio       0
Outstanding_Debt               0
Credit_Mix                     0
Changed_Credit_Limit           0
Age                            0
Num_of_Delayed_Payment         0
dtype: int64

In [60]:
# 1) Variable objetivo
y = df["Credit_Score"]

# 2) Variables de entrada (todas menos la etiqueta)
X = df.drop(columns=["Credit_Score"])

X.shape, y.shape

((100000, 24), (100000,))

In [61]:
# 3) Columnas categóricas de X (después de todas las conversiones)
cat_cols = X.select_dtypes(include=["object"]).columns
cat_cols

Index(['Month', 'Occupation', 'Type_of_Loan', 'Credit_Mix',
       'Payment_of_Min_Amount', 'Payment_Behaviour'],
      dtype='object')

In [62]:
# 4) One-Hot Encoding de las categóricas
X_dummies = pd.get_dummies(X, columns=cat_cols, drop_first=True)

X_dummies.shape

(100000, 6305)

# MODELO RANDOM FOREST Y REGRESION LOGISTA

In [64]:
X_model = X_dummies

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_model, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [66]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_recall_fscore_support
import pandas as pd

# --- Modelo 1: Regresión Logística ---
log_clf = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    multi_class="multinomial",
    solver="lbfgs"
)

log_clf.fit(X_train, y_train)

y_test_pred_log = log_clf.predict(X_test)

C:\Users\COMPU\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

KeyboardInterrupt:

In [ ]:
# --- Modelo 2: Random Forest ---
rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight="balanced",
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)

y_test_pred_rf = rf.predict(X_test)

# --- Tabla comparativa ---
prec_log, rec_log, f1_log, _ = precision_recall_fscore_support(
    y_test, y_test_pred_log, average="macro"
)
acc_log = accuracy_score(y_test, y_test_pred_log)

prec_rf, rec_rf, f1_rf, _ = precision_recall_fscore_support(
    y_test, y_test_pred_rf, average="macro"
)
acc_rf = accuracy_score(y_test, y_test_pred_rf)

tabla_modelos = pd.DataFrame({
    "Modelo": ["LogisticRegression", "RandomForest"],
    "Accuracy": [acc_log, acc_rf],
    "Precision_macro": [prec_log, prec_rf],
    "Recall_macro": [rec_log, rec_rf],
    "F1_macro": [f1_log, f1_rf]
})

tabla_modelos